---
name: CI

on:
  workflow_dispatch:
  push:
    branches: ["main"]
    paths:
      - "go.mod"
      - "go.sum"
      - "*.go"
      - "**/*.go"
      - ".golangci.yml"
  pull_request:
    branches: ["main"]
  merge_group:
    branches: ["main"]

jobs:
  lint:
    uses: heathcliff26/ci/.github/workflows/golang-lint.yaml@main
    permissions:
      contents: read

  unit-tests:
    uses: heathcliff26/ci/.github/workflows/golang-unit-tests.yaml@main
    permissions:
      contents: read
    with:
      coveralls: ${{ github.event_name == 'pull_request' || github.event_name == 'merge_group' }}

  validate:
    uses: heathcliff26/ci/.github/workflows/golang-build.yaml@main
    permissions:
      contents: read
    with:
      cache: false
      cmd: "make validate"
