---
name: Run golangci

on:
  workflow_dispatch:
  workflow_call:
  push:
    branches: [main]
    paths:
      - "go.mod"
      - "go.sum"
      - "*.go"
      - ".golangci.yml"
  pull_request:
    branches: [main]
    paths:
      - "go.mod"
      - "go.sum"
      - "*.go"
      - ".golangci.yml"
      - ".github/workflows/ci.yaml"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5.0.0
        with:
          go-version: 'stable'
          cache-dependency-path: go.sum

      - name: golangci-lint
        uses: golangci/golangci-lint-action@3a919529898de77ec3da873e3063ca4b10e7f5cc # v3.7.0
        with:
          version: latest
          args: --config=.golangci.yml
          skip-cache: true

  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5.0.0
        with:
          go-version: 'stable'
          cache-dependency-path: go.sum

      - name: run tests
        run: go test -v ./...
