---
name: CI

on:
  workflow_dispatch:
  push:
    branches: ["main"]
    paths:
      - "go.mod"
      - "go.sum"
      - "*.go"
      - "**/*.go"
      - ".golangci.yml"
  pull_request:
    branches: ["main"]
  merge_group:
    branches: ["main"]

jobs:
  lint:
    uses: heathcliff26/ci/.github/workflows/golang-lint.yaml@main

  unit-tests:
    uses: heathcliff26/ci/.github/workflows/golang-unit-tests.yaml@main
    with:
      cmd: go test -v -race ./...
