
---
name: "Labels Check"

on:
  workflow_dispatch:
  pull_request:
    branches: ["main"]
    types:
      - opened
      - synchronize
      - reopened
      - labeled
      - unlabeled

jobs:
  check-labels:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    steps:
      - name: Check for do-not-merge
        id: do-not-merge
        uses: docker://agilepathway/pull-request-label-checker:v1.6.13
        with:
          repo_token: ${{ github.token }}
          none_of: do-not-merge
